### ISSUE TITLE
Windows 10: AttributeError: 'module' object has no attribute 'STARTF_USESHOWWINDOW'

### ISSUE THREAD

**Issue by petachew** [blink1073/oct2py#130]
>>> from oct2py import octave

Traceback (most recent call last):
  File "<pyshell#0>", line 1, in <module>
    from oct2py import octave
  File "C:\Python27\lib\site-packages\oct2py\__init__.py", line 38, in <module>
    octave = Oct2Py()
  File "C:\Python27\lib\site-packages\oct2py\core.py", line 73, in __init__
    self.restart()
  File "C:\Python27\lib\site-packages\oct2py\core.py", line 508, in restart
    logger=self.logger)
  File "C:\Python27\lib\site-packages\octave_kernel\kernel.py", line 144, in __init__
    self.repl = self._create_repl()
  File "C:\Python27\lib\site-packages\octave_kernel\kernel.py", line 352, in _create_repl
    stdin_prompt_regex=STDIN_PROMPT_REGEX)
  File "C:\Python27\lib\site-packages\metakernel\replwrap.py", line 65, in __init__
    encoding="utf-8")
  File "C:\Python27\lib\site-packages\metakernel\pexpect.py", line 31, in spawn
    encoding=encoding, codec_errors=codec_errors)
  File "C:\Python27\lib\site-packages\pexpect\popen_spawn.py", line 38, in __init__
    startupinfo.dwFlags |= subprocess.STARTF_USESHOWWINDOW
AttributeError: 'module' object has no attribute 'STARTF_USESHOWWINDOW'

**Comment by blink1073** [comment]
Hi @petachew, I'm not sure why that wouldn't exist.  There's not much I can do from here, it would have to be handled in [pexpect](https://github.com/pexpect/pexpect).
