### ISSUE TITLE
sys vs oct2py incompatibility?

### ISSUE THREAD

**Issue by ppebay** [blink1073/oct2py#131]
**1. Problem Statement:**
$ python
Python 2.7.10 (default, Jul 14 2015, 19:46:27) 
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.39)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> import oct2py
>>> a=0
>>> ^D

**2. Observed Errors:**
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/metakernel/replwrap.py", line 194, in terminate
    self.child.close()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pexpect/pty_spawn.py", line 318, in close
    self.ptyproc.close(force=force)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/ptyprocess/ptyprocess.py", line 391, in close
    raise PtyProcessError('Could not terminate the child.')
PtyProcessError: Could not terminate the child.
Error in sys.exitfunc:
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/metakernel/replwrap.py", line 194, in terminate
    self.child.close()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pexpect/pty_spawn.py", line 318, in close
    self.ptyproc.close(force=force)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/ptyprocess/ptyprocess.py", line 391, in close
    raise PtyProcessError('Could not terminate the child.')
ptyprocess.ptyprocess.PtyProcessError: Could not terminate the child.

**3. Important Note:**
It is important that at least one instruction be executed prior to exiting Python (otherwise, the error does **not** manifest itself), whence the a=0 assignment. 

**4. Questions:**
- Is this a known issue [_NB: I could not find anything even with an extensive web search_]?
- Is there a known remedy?

Thank you
PPP

**Comment by blink1073** [comment]
I've not seen that before, and I'm not sure what would cause it.  I use OSX as well, but not the system python.

```
$ python
Python 3.5.2 |Anaconda custom (x86_64)| (default, Jul  2 2016, 17:52:12)
[GCC 4.2.1 Compatible Apple LLVM 4.2 (clang-425.0.28)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>>
```

**Comment by ppebay** [comment]
Thank you for the response.

I tried with another MacOS platform (with 10.12 this time, whereas for my initial message it was with 10.10), got the same error.

However I noticed that you are not seeing the problem with Python 3.5, may I ask what happens with your custom version of Python 2.7?

Thank you

**Comment by blink1073** [comment]
Works with Python 2.7 as well.  Note that the above doesn't affect runtime behavior, but it might mean that the Octave process is left open.

**Comment by ppebay** [comment]
Thanks. I was wondering about that. So, is the mere fact of executing one assignment (in the case above, "a=0") sufficient to launch the Octave process, although it was not called out explicitly?

Only importing the 2 packages, but not executing any command before exiting, does not create the problem mentioned above. So, presumably, any operation (even not using oct2py) is sufficient to launch an Octave process -- is it so?

Thanks

**Comment by blink1073** [comment]
Importing from `oct2py` has the side effect of starting a process for the default `octave` instance (`from oct2py import octave`).

**Comment by ppebay** [comment]
All right, so this is entirely consistent with what I am seeing. Thank you for confirming that.

So, I am left with this problem of Octave processes left open upon exit from Python. Even calling kill_octave() **twice** does not always resolve the issue; at times it does, but in any case, if I call kill_octave() **once**, then it is never sufficient to obtain a graceful exit.

I have been able to replicate this behavior on two different MacOS versions (10.10 and 10.12) and with the vanilla install of Python 2.7. Do you have an idea as to where I should look in order to try to fix this problem (which albeit not affecting runtime results, is nonetheless causing other problems because of non-regression testing that fails as a result of this unclean exit).
 
Happy Fourth
PPP

**Comment by blink1073** [comment]
This is the line in `ptyprocess` that is throwing the error on shutdown: https://github.com/pexpect/ptyprocess/blob/b9b03b79a511bb2a1b405f00b36516551be1ea2c/ptyprocess/ptyprocess.py#L395.  I'm not entirely sure why it wouldn't shut down properly.

**Comment by ppebay** [comment]
Hello. Yes indeed, the error is thrown by` ptyprocess`, but what I fail to understand is how this relates to oct2py. The call stack at the time of error is as follows:

```
File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/metakernel/replwrap.py", line 194, in terminate
    self.child.close()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pexpect/pty_spawn.py", line 318, in close
    self.ptyproc.close(force=force)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/ptyprocess/ptyprocess.py", line 391, in close
    raise PtyProcessError('Could not terminate the child.')
ptyprocess.ptyprocess.PtyProcessError: Could not terminate the child.

```

but why is this even related to oct2py?

**Comment by blink1073** [comment]
We are using `pytprocess` to spawn the `Octave` process.  We create an `atexit` handler to make sure the `Octave` gets properly terminated when the `python` process exits.  However, it does not seem to be working on your system.

**Comment by ppebay** [comment]
All right -- now I have all the pieces, thank you for these explanations. I am going to try to dig up what's going on exactly with the `atexit` (which indeed is what triggers the cascade of exceptions).

**Comment by SnailBones** [comment]
I encountered no apparent issues on MacOS with HomeBrew, this may be an issue exclusive to MacPorts.

**Comment by andrescodas** [comment]
Do you have news on this issue?

(Only) when I call python in debug mode I get the error:

----------------------------------------------------------
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.13_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/usr/local/lib/python2.7/site-packages/metakernel/replwrap.py", line 194, in terminate
    return self.child.terminate()
  File "/usr/local/lib/python2.7/site-packages/pexpect/pty_spawn.py", line 603, in terminate
    time.sleep(self.delayafterterminate)
KeyboardInterrupt
Error in sys.exitfunc:
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.13_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/usr/local/lib/python2.7/site-packages/metakernel/replwrap.py", line 194, in terminate
    return self.child.terminate()
  File "/usr/local/lib/python2.7/site-packages/pexpect/pty_spawn.py", line 603, in terminate
    time.sleep(self.delayafterterminate)
KeyboardInterrupt
----------------------------------------------------------

I have some small unit-testing functions creating instances of oct2py.Oct2Py.  I have been monitoring the processes and I saw that the instances are destroyed when the whole python execution is closed and not when the objects go out of scope.  Further, I see that self._engine.repl.terminate() returns always False

**Comment by ppebay** [comment]
Hello,

Thank you for the post -- at least I know someone else is encountering the same issue. 

It is noticeable that in your case it only happens in debug mode. On my systems it always happens (with the MacPorts distribution). 

May I ask you what system/distribution you are using? 

Thank you
Philippe PEBAY

**Comment by andrescodas** [comment]
@ppebay 

MacOS Sierra Version 10.12.6
Octave version 4.2.1 installed with 'brew install octave'
Python 2.7.13

**Comment by ppebay** [comment]
@andrescodas 
@blink1073 
My apologies for having dropped a ball for a while, I was busy with other things. I just resumed looking at this Oct2Py problem, hoping it might have been fixed in the meantime.

I am using Mac OS Yosemite (10.10.5), Octave 4.2.1 like you, but installed with MacPorts (port install), and Python 2.7.10, and getting error messages very similar to yours:

Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/metakernel/replwrap.py", line 194, in terminate
    self.child.close()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pexpect/pty_spawn.py", line 318, in close
    self.ptyproc.close(force=force)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/ptyprocess/ptyprocess.py", line 393, in close
    raise PtyProcessError('Could not terminate the child.')
PtyProcessError: Could not terminate the child.
Error in sys.exitfunc:
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/metakernel/replwrap.py", line 194, in terminate
    self.child.close()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pexpect/pty_spawn.py", line 318, in close
    self.ptyproc.close(force=force)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/ptyprocess/ptyprocess.py", line 393, in close
    raise PtyProcessError('Could not terminate the child.')
ptyprocess.ptyprocess.PtyProcessError: Could not terminate the child.

My case is similar to yours, with non-regression testing units instantiating oct2py Octave sessions; and terminate() also always returns false. I think this qualifies for a bug.

**Comment by blink1073** [comment]
This can be fixed by running `pip install -U oct2py octave_kernel`.

**Comment by ppebay** [comment]
Thank you for having resolved the issue. 

On 2019-05-03 11:04, Steven Silvester wrote:

> This can be fixed by running pip install -U oct2py octave_kernel. 
> 
> --
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub [1], or mute the thread [2].
 

Links:
------
[1]
https://github.com/blink1073/oct2py/issues/131#issuecomment-489127282
[2]
