### ISSUE TITLE
Problems importing the oct2py python package

### ISSUE THREAD

**Issue by Wallflower123** [blink1073/oct2py#177]
Hello, I am having problems importing oct2py package in my python script.
Whenever `import oct2py` is run I get the following error:
`>>> import oct2py
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Program Files\Python37\lib\site-packages\oct2py\__init__.py", line 38, in <module>
    octave = Oct2Py()
  File "C:\Program Files\Python37\lib\site-packages\oct2py\core.py", line 76, in __init__
    self.restart()
  File "C:\Program Files\Python37\lib\site-packages\oct2py\core.py", line 521, in restart
    logger=self.logger)
  File "C:\Program Files\Python37\lib\site-packages\octave_kernel\kernel.py", line 173, in __init__
    self.repl = self._create_repl()
  File "C:\Program Files\Python37\lib\site-packages\octave_kernel\kernel.py", line 392, in _create_repl
    force_prompt_on_continuation=True)
  File "C:\Program Files\Python37\lib\site-packages\metakernel\replwrap.py", line 63, in __init__
    encoding="utf-8")
  File "C:\Program Files\Python37\lib\site-packages\metakernel\pexpect.py", line 32, in spawn
    encoding=encoding, codec_errors=codec_errors)
  File "C:\Program Files\Python37\lib\site-packages\pexpect\popen_spawn.py", line 53, in __init__
    self.proc = subprocess.Popen(cmd, **kwargs)
  File "C:\Program Files\Python37\lib\subprocess.py", line 756, in __init__
    restore_signals, start_new_session)
  File "C:\Program Files\Python37\lib\subprocess.py", line 1155, in _execute_child
    startupinfo)
OSError: [WinError 193] %1 n’est pas une application Win32 valide`

Any ideas?

Thanks in advance!

**Comment by dmkriete** [comment]
@Wallflower123 were you able to resolve this issue? I'm encountering the exact same error and have not been able to fix it.

**Comment by Wallflower123** [comment]
@dmkriete Yes, I started using Anaconda and Spyder instead of my own python installation.

**Comment by dmkriete** [comment]
@Wallflower123 Hmmmm I am already using Anaconda and Spyder, and I have tried many different versions. Could you tell me which version of Anaconda, oct2py, and octave you have it working on?

**Comment by Wallflower123** [comment]
@dmkriete Hmm weird, I am on Windows and using the latest version of Anaconda...
Have you tried uninstalling and re-installing Anaconda? Also, do not forget to run the command prompt as an administrator and delete the Temp folder if your on Windows too..

**Comment by dmkriete** [comment]
@Wallflower123 Yes, I have tried uninstalling and re-installing Python, Anaconda, and Octave several times (using different versions), all without success.

**Comment by Wallflower123** [comment]
@dmkriete Maybe Skype so we can see together? But not now...
