### ISSUE TITLE
OSError: [WinError 193] %1 is not a valid Win32 application

### ISSUE THREAD

**Issue by madbot69** [blink1073/oct2py#188]
Hi there,

Installed oct2py on 2 different Windows 10 machines. One works with oct2py fine, but the other machine keeps coming up with the OSError at :

`from oct2py import octave`

 The code is run from PyCharm. Same setup on both machines.

config: OS: Windows 10 (64 bit),
oct2py: 5.2.0,
Python: 3.8.7 (tried both 64 bit and 32bit), octave: 6.1.0 (64 bit)
Pycharm: 2020.3.5

Have re-installed python, PyCharm, adjusted PATH statement multiple times on the second machine but still getting the same error. Below is the lines returned. Any help would be greatly appreciated...

`C:\Storage\python\python.exe C:/Users/XXX/PycharmProjects/test2/main.py
Traceback (most recent call last):
  File "C:/Users/XXX/PycharmProjects/test2/main.py", line 18, in <module>
    from oct2py import octave
  File "C:\Storage\python\lib\site-packages\oct2py\__init__.py", line 38, in <module>
    octave = Oct2Py()
  File "C:\Storage\python\lib\site-packages\oct2py\core.py", line 76, in __init__
    self.restart()
  File "C:\Storage\python\lib\site-packages\oct2py\core.py", line 520, in restart
    self._engine = OctaveEngine(stdin_handler=self._handle_stdin,
  File "C:\Storage\python\lib\site-packages\octave_kernel\kernel.py", line 173, in __init__
    self.repl = self._create_repl()
  File "C:\Storage\python\lib\site-packages\octave_kernel\kernel.py", line 390, in _create_repl
    repl = REPLWrapper(cmd, orig_prompt, change_prompt,
  File "C:\Storage\python\lib\site-packages\metakernel\replwrap.py", line 61, in __init__
    self.child = pexpect.spawnu(cmd_or_spawn, echo=echo,
  File "C:\Storage\python\lib\site-packages\metakernel\pexpect.py", line 29, in spawn
    child = PopenSpawn(command, timeout=timeout, maxread=maxread,
  File "C:\Storage\python\lib\site-packages\pexpect\popen_spawn.py", line 53, in __init__
    self.proc = subprocess.Popen(cmd, **kwargs)
  File "C:\Storage\python\lib\subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Storage\python\lib\subprocess.py", line 1307, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
OSError: [WinError 193] %1 is not a valid Win32 application

Process finished with exit code 1`

**Comment by madbot69** [comment]
Eventually found a solution for my case, although I don't understand why it works on one computer but not the other.. but just in case this helps someone else with the same problem.

Octave was originally installed at the default location, ie. "C:\Program Files\GNU Octave\Octave" ... and so on.

Had a thought that perhaps the command to call Octave was getting tripped up with the space in the path name and re-installed Octave at a path without space at (for example) c:\xxx\Octave and ensured there were no space in the path name during Octave installation.

And it worked. No more error from oct2py.

Not sure which solved it: re-installing Octave, or ensuring no "space" in the path name.

It works now and I am going on my merry way.
