### ISSUE TITLE
initialization: graphics_toolkit: 2004h toolkit is not available

### ISSUE THREAD

**Issue by pirofti** [blink1073/oct2py#237]
Hi,

I just updated `oct2py` and `Octave` on my system and I get the following error in `python` and `jupyter` whenever I try to execute an `oct2py` command.

```
$ python -i
Python 3.10.4 (main, Mar 23 2022, 23:05:40) [GCC 11.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import oct2py
>>> oc = oct2py.Oct2Py()
>>> x = oc.zeros(3,3)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.10/site-packages/oct2py/core.py", line 758, in __getattr__
    exist = self._exist(name)
  File "/usr/lib/python3.10/site-packages/oct2py/core.py", line 709, in _exist
    exist = int(resp.split()[-1])
ValueError: invalid literal for int() with base 10: '\x1b[?2004h'
```

The problem is, I think the communication between `oct2py` and `Octave`.
```
$ ipython
Python 3.10.4 (main, Mar 23 2022, 23:05:40) [GCC 11.2.0]
Type 'copyright', 'credits' or 'license' for more information
IPython 8.2.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import oct2py

In [2]: oc = oct2py.Oct2Py()

In [3]: x = oc.zeros(3,3)
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Input In [3], in <cell line: 1>()
----> 1 x = oc.zeros(3,3)

File /usr/lib/python3.10/site-packages/oct2py/core.py:758, in Oct2Py.__getattr__(self, attr)
    755     raise Oct2PyError('Session is closed')
    757 # Make sure the name exists.
--> 758 exist = self._exist(name)
    760 if exist not in [2, 3, 5, 103]:
    761     msg = 'Name "%s" is not a valid callable, use `pull` for variables'

File /usr/lib/python3.10/site-packages/oct2py/core.py:709, in Oct2Py._exist(self, name)
    707 cmd = 'exist("%s")' % name
    708 resp = self._engine.eval(cmd, silent=True).strip()
--> 709 exist = int(resp.split()[-1])
    710 if exist == 0:
    711     cmd = 'class(%s)' % name

ValueError: invalid literal for int() with base 10: '\x1b[?2004h'

In [4]: debug
> /usr/lib/python3.10/site-packages/oct2py/core.py(709)_exist()
    707         cmd = 'exist("%s")' % name
    708         resp = self._engine.eval(cmd, silent=True).strip()
--> 709         exist = int(resp.split()[-1])
    710         if exist == 0:
    711             cmd = 'class(%s)' % name

ipdb> name
'zeros'
ipdb> resp
'\x1b[?2004l\rans = 5\r\n\x1b[?2004h'
```

I get this with any other method that might be the first to run after `oct2py` is initialized (e.g. `available_graphics_toolkits`, `ones`). The faulty string never changes, it always has the same value. These commands run just fine in `Octave`, so I think it is a communication issue.

Any tips of what I might try next?

Thank you,
Paul

**Comment by blink1073** [comment]
Hi @pirofti, what OS and what version of Octave are you using?  It looks like we need to add handling for those control characters.  This issue looks relevant: https://github.com/pexpect/pexpect/issues/669

**Comment by pirofti** [comment]
@blink1073, I am using an `ArchLinux 5.17.3-arch1-1` and `Octave 7.1.0`. Both updated today.

**Comment by pirofti** [comment]
> Hi @pirofti, what OS and what version of Octave are you using? It looks like we need to add handling for those control characters. This issue looks relevant: [pexpect/pexpect#669](https://github.com/pexpect/pexpect/issues/669)

This [workaround](https://github.com/pexpect/pexpect/issues/669#issuecomment-758109973) from the issue you mentioned, indeed, fixes the issue for me.

**Comment by blink1073** [comment]
Great, thanks for verifying.  I think that might be the best we can do, based on this [response](https://github.com/pexpect/pexpect/issues/669#issuecomment-868950111).

**Comment by pirofti** [comment]
Right. I don't know what this new feature is supposed to do, but disabling it everywhere seems wrong also. Anyway you decide to go, it should probably be in the documentation as well so that us users can find it quickly.

Thank you for looking into this!
