### ISSUE TITLE
Run doesn't create new variables in the octave environment

### ISSUE THREAD

**Issue by WiserOrb** [blink1073/oct2py#239]
Hi, when executing .m files with `octave.run('test')`, I cannot pull variables from the octave syntax that the script should have populated.
Is this the expected behavior? When I use the same command in octave it keeps the variables.
Also if I use `eval` it populates the variables, but it too has problems because it cannot plot graphs, a requirement in my application.
Am I doing anything wrong?

test.m
```mat
a = [1,2,3];
```

Python code
```py

from oct2py import octave as oc

oc.run('test')
oc.pull('a')
```

Output:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/diego/.local/lib/python3.10/site-packages/oct2py/core.py", line 194, in pull
    exist = self._exist(name)
  File "/home/diego/.local/lib/python3.10/site-packages/oct2py/core.py", line 715, in _exist
    raise Oct2PyError(msg % name)
oct2py.utils.Oct2PyError: Value "a" does not exist in Octave workspace
```

P.S.
Thank you for developing this library.

**Comment by blink1073** [comment]
Hi @WiseroOrb, thanks for the kind words.

Yes, this is an unfortunate limitation of the way we're evaluating the script.  If you need a result you'd have to use a function.  Something like:

test.m

```matlab
function a = test()
   a = [1,2,3];
end
```

test.py

```python
from oct2py import octave as oc
a = oc.test()
print(a)
```

Which gives:  `[[1. 2. 3.]]`

**Comment by WiseroOrb** [comment]
Hi @blink1073 ,
So I'm in the process of converting the script in the way you suggested, however I've encountered a major roadblock:  I need to return an object from the `statistical` package, of class `gmdistribution`. Oct2py trows some warning when I try to return it, and later fails to use it in other functions.
I think the origin of the problem is because this class doesn't implement saveobj.

Right now I'm planning to do use `eval(distribution = computeDistribution(args))` and keeping the distribution object in the octave workspace.

This pollutes the way I call the functions, because from now on I need to push/pull every argument and use the eval statement every time I need to use the distribution object.

I thought of treating it as a global variable and not as a funtion paramenter, but this requires writing wrappers for each affected function.

Do you have any better solution?

**Comment by blink1073** [comment]
The only other option I can see if there is if you can serialize the gmdistribution data yourself by extracting properties into a cell object.
