### ISSUE TITLE
bracketed paste \x1b[?2004h issue

### ISSUE THREAD

**Issue by prowe12** [blink1073/oct2py#248]
I just installed octave and oct2py on a new Mac with the m1 chip and MacOS Monterey Version 12.4.

I am getting the error: 

Traceback (most recent call last):
  File "/Users/prowe/git-repos/mpl-processing/tests/test_oct2py/test_oct2py.py", line 17, in <module>
    oc.addpath(os.getcwd() + '/tests/test_oct2py/')
  File "/opt/homebrew/lib/python3.9/site-packages/oct2py/core.py", line 758, in __getattr__
    exist = self._exist(name)
  File "/opt/homebrew/lib/python3.9/site-packages/oct2py/core.py", line 709, in _exist
    exist = int(resp.split()[-1])
ValueError: invalid literal for int() with base 10: '\x1b[?2004h'

This seems to be due to "\x1b[?2004h" being appended to the beginning and ending of the result of self._engine.eval(cmd, silent=True).strip().

Thus when exist = int(resp.split()[-1]) is run, the final character is '\x1b[?2004h' instead of, e.g. 5 for addpath.

Is there a fix or work-around?

Thank you!

**Comment by blink1073** [comment]
Hi @prowe12, this is a known issue, the workaround is here: https://github.com/pexpect/pexpect/issues/669#issuecomment-758109973

**Comment by prowe12** [comment]
Thank you so much!  It worked.  I'm sorry I missed the known issue - I did spend a lot of time looking but didn't know the keywords to use.

**Comment by blink1073** [comment]
No worries!  Yeah it is a hard thing to search for. 😃
