### ISSUE TITLE
Tests failing in Python 3.4 on Ubuntu 12.04

### ISSUE THREAD

**Issue by andrewclegg** [blink1073/oct2py#44]
When I run

    python3.4 `which iptest3` --all -j

from a [Snake Charmer](https://github.com/andrewclegg/snake-charmer) VM, I get:

```
======================================================================
ERROR: IPython.extensions.tests.test_octavemagic.test_octave_roundtrip
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/usr/local/lib/python3.4/dist-packages/IPython/extensions/tests/test_octavemagic.py", line 33, in test_octave_roundtrip
    ip.run_line_magic('octave_push', 'x y')
  File "/usr/local/lib/python3.4/dist-packages/IPython/core/interactiveshell.py", line 2126, in run_line_magic
    result = fn(*args,**kwargs)
  File "<string>", line 2, in octave_push
  File "/usr/local/lib/python3.4/dist-packages/IPython/core/magic.py", line 193, in <lambda>
    call = lambda f, *a, **k: f(*a, **k)
  File "/usr/local/lib/python3.4/dist-packages/IPython/extensions/octavemagic.py", line 145, in octave_push
    self._oct.put(input, self.shell.user_ns[input])
  File "/usr/local/lib/python3.4/dist-packages/oct2py/session.py", line 289, in put
    self._eval(load_line, verbose=verbose, timeout=timeout)
  File "/usr/local/lib/python3.4/dist-packages/oct2py/session.py", line 395, in _eval
    timeout=timeout)
  File "/usr/local/lib/python3.4/dist-packages/oct2py/session.py", line 647, in evaluate
    raise Oct2PyError(msg)
oct2py.utils.Oct2PyError: Oct2Py tried to run:
"""
load /tmp/tmprl5sx8op.mat "y"
"""
Octave returned:
load: unable to find file /tmp/tmprl5sx8op.mat

======================================================================
ERROR: IPython.extensions.tests.test_octavemagic.test_octave_cell_magic
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/usr/local/lib/python3.4/dist-packages/IPython/extensions/tests/test_octavemagic.py", line 44, in test_octave_cell_magic
    'z = x + y;')
  File "/usr/local/lib/python3.4/dist-packages/IPython/core/interactiveshell.py", line 2162, in run_cell_magic
    result = fn(magic_arg_s, cell)
  File "<string>", line 2, in octave
  File "/usr/local/lib/python3.4/dist-packages/IPython/core/magic.py", line 193, in <lambda>
    call = lambda f, *a, **k: f(*a, **k)
  File "/usr/local/lib/python3.4/dist-packages/IPython/extensions/octavemagic.py", line 270, in octave
    self._oct.put(input, val)
  File "/usr/local/lib/python3.4/dist-packages/oct2py/session.py", line 289, in put
    self._eval(load_line, verbose=verbose, timeout=timeout)
  File "/usr/local/lib/python3.4/dist-packages/oct2py/session.py", line 395, in _eval
    timeout=timeout)
  File "/usr/local/lib/python3.4/dist-packages/oct2py/session.py", line 647, in evaluate
    raise Oct2PyError(msg)
oct2py.utils.Oct2PyError: Oct2Py tried to run:
"""
load /tmp/tmp03y794ri.mat "y"
"""
Octave returned:
load: unable to find file /tmp/tmp03y794ri.mat

----------------------------------------------------------------------
```

Steps:

Clone Snake Charmer: https://github.com/andrewclegg/snake-charmer.git

Checkout this revision (so as to avoid any confounding factors): 7d5e90e8b8816b0a28b037cf3094cdf4f24bf19f

Start up a VM: `vagrant up`

... wait about an hour ...

Log in to new VM:

    vagrant ssh

Run tests:

    python3.4 `which iptest3` --all -j

When I kick off the tests from within an IPython Notebook, this doesn't happen. Should it just be skipping these tests when you're not in a notebook?

**Comment by blink1073** [comment]
Fixed upstream.
